version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-2:144302571462:task-definition/ec2-task-definition:1"
        LoadBalancerInfo:
          ContainerName: "nginx"
          ContainerPort: 8000
# Optional properties
        # PlatformVersion: "LATEST"
        # NetworkConfiguration:
        #   AwsvpcConfiguration:
        #     Subnets: ["subnet-1234abcd","subnet-5678abcd"]
        #     SecurityGroups: ["sg-12345678"]
        #     AssignPublicIp: "ENABLED"
        # CapacityProviderStrategy:
        #   - Base: 1
        #     CapacityProvider: "FARGATE_SPOT"
        #     Weight: 2
        #   - Base: 0
        #     CapacityProvider: "FARGATE"
        #     Weight: 1
Hooks:
  - BeforeInstall: "LambdaFunctionToValidateBeforeInstall"
  - AfterInstall: "LambdaFunctionToValidateAfterInstall"
  - AfterAllowTestTraffic: "LambdaFunctionToValidateAfterTestTrafficStarts"
  - BeforeAllowTraffic: "LambdaFunctionToValidateBeforeAllowingProductionTraffic"
  - AfterAllowTraffic: "LambdaFunctionToValidateAfterAllowingProductionTraffic"