DROP DATABASE IF EXISTS chat_test;
CREATE DATABASE IF NOT EXISTS chat_test CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
DROP DATABASE IF EXISTS chat_local;
CREATE DATABASE IF NOT EXISTS chat_local CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
